
export const menulist= [
  {
    path:'/market',
    name:'市场',
    permission:'1',
  },
  {
    path:'/market/service',
    name:'数据录入',
    permission:'6',
  },
  {
    path:'/market/source',
    name:'来源设置',
    permission:'7',
  },
  {
    path:'/market/set',
    name:'客户量设置',
    permission:'8',
  },
  {
    path:'/market/bidding',
    name:'竞价数据',
    permission:'107',
  },
  {
    path:'/market/analysis',
    name:'数据分析',
    permission:'9',
  },
  {
    path:'/userCenter',
    name:'设置',
    permission:'44',
  },
  {
    path:'/userCenter/index',
    name:'用户设置',
    permission:'45',
  },
  {
    path:'/userCenter/team',
    name:'组员管理',
    permission:'46',
  },
  {
    path:'/userCenter/message',
    name:'消息中心',
    permission:'47',
  },
  {
    path:'/manager',
    name:'系统设置',
    permission:'50',
  },
  {
    path:'/manager/tree-list',
    name:'员工与部门管理',
    permission:'51',
  },
  {
    path:'/manager/role',
    name:'角色权限控制',
    permission:'52',
  },
  {
    path:'/manager/menu',
    name:'菜单管理',
    permission:'53',
  }
]

